;;; agent-review-entrypoint-test.el --- Entrypoint tests -*- lexical-binding: t; -*-

(require 'test-helper)

(ert-deftest agent-review-creates-a-new-offline-review ()
  (should (fboundp 'agent-review))
  (agent-review-test-with-temp-repo (repo)
    (let ((default-directory repo)
          (buffer nil))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _args) "main"))
                ((symbol-function 'switch-to-buffer)
                 (lambda (buf &rest _)
                   (setq buffer (get-buffer buf))))
                ((symbol-function 'pop-to-buffer)
                 (lambda (buf &rest _)
                   (setq buffer (get-buffer buf)))))
        (setq buffer (agent-review))
        (should (buffer-live-p buffer))
        (with-current-buffer buffer
          (should (derived-mode-p 'agent-review-mode))
          (should (string-match-p "Base: main" (buffer-string)))
          (should (string-match-p "diff --git" (buffer-string)))))
      (let ((review-file (expand-file-name ".agent-review/feature/offline.json" repo)))
        (should (file-exists-p review-file))))))

(ert-deftest agent-review-continues-or-replaces-existing-review ()
  (should (fboundp 'agent-review-store-read))
  (agent-review-test-with-temp-repo (repo)
    (let* ((head (agent-review-test--git repo "rev-parse" "HEAD"))
           (review-file (expand-file-name ".agent-review/feature/offline.json" repo))
           (seed (agent-review-test--sample-review repo "feature/offline" "main" head (list head))))
      (setf (alist-get 'events seed)
            '(((kind . "created")
               (created_at . "2026-03-29T00:00:00Z"))
              ((kind . "thread_replied")
               (created_at . "2026-03-29T00:05:00Z")
               (thread_id . "thread-seed"))))
      (agent-review-test--write-review-file review-file seed)
      (let ((default-directory repo)
            (continue-buffer nil))
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (prompt &rest _)
                     (if (string-match-p "Existing review" prompt)
                         "Continue"
                       (ert-fail "base prompt should not be used on Continue"))))
                  ((symbol-function 'switch-to-buffer)
                   (lambda (buf &rest _) (setq continue-buffer (get-buffer buf))))
                  ((symbol-function 'pop-to-buffer)
                   (lambda (buf &rest _) (setq continue-buffer (get-buffer buf)))))
          (setq continue-buffer (agent-review))
          (with-current-buffer continue-buffer
            (should (string-match-p "Base: main" (buffer-string)))))
        (should (equal "review-seed"
                       (alist-get 'review_id (agent-review-store-read review-file)))))
      (let ((default-directory repo)
            (replace-buffer nil)
            (responses '("Replace" "HEAD~1")))
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (&rest _args)
                     (prog1 (car responses)
                       (setq responses (cdr responses)))))
                  ((symbol-function 'switch-to-buffer)
                   (lambda (buf &rest _) (setq replace-buffer (get-buffer buf))))
                  ((symbol-function 'pop-to-buffer)
                   (lambda (buf &rest _) (setq replace-buffer (get-buffer buf)))))
          (setq replace-buffer (agent-review))
          (with-current-buffer replace-buffer
            (should (string-match-p "Base: HEAD~1" (buffer-string)))))
        (let ((review (agent-review-store-read review-file)))
          (should (equal "HEAD~1" (alist-get 'base_ref review)))
          (should-not (equal "review-seed" (alist-get 'review_id review)))
          (should (equal '("created" "thread_replied" "created" "replaced")
                         (mapcar (lambda (event) (alist-get 'kind event))
                                 (alist-get 'events review)))))))))

(ert-deftest agent-review-open-compatibility-entrypoint-is-callable ()
  (should (fboundp 'agent-review-open))
  (should (fboundp 'agent-review-open-url))
  (agent-review-test-with-temp-repo (repo)
    (let ((default-directory repo)
          (buffer nil))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _args) "main"))
                ((symbol-function 'switch-to-buffer)
                 (lambda (buf &rest _)
                   (setq buffer (get-buffer buf))))
                ((symbol-function 'pop-to-buffer)
                 (lambda (buf &rest _)
                   (setq buffer (get-buffer buf)))))
        (setq buffer (agent-review-open "owner" "repo" 123 t "anchor" "last-read"))
        (should (buffer-live-p buffer))
        (with-current-buffer buffer
          (should (derived-mode-p 'agent-review-mode)))
        (should (buffer-live-p (agent-review-open-url "https://example.test/pr/123")))))))

(ert-deftest agent-review-context-commands-persist-immediately ()
  (should (fboundp 'agent-review-context-comment))
  (should (fboundp 'agent-review-toggle-thread-state))
  (agent-review-test-with-temp-repo (repo)
    (let ((default-directory repo)
          (responses '("main" "Needs attention" "Reply from agent"))
          (buffer nil))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _args)
                   (prog1 (car responses)
                     (setq responses (cdr responses)))))
                ((symbol-function 'read-string)
                 (lambda (&rest _args)
                   (prog1 (car responses)
                     (setq responses (cdr responses)))))
                ((symbol-function 'switch-to-buffer)
                 (lambda (buf &rest _) (setq buffer (get-buffer buf))))
                ((symbol-function 'pop-to-buffer)
                 (lambda (buf &rest _) (setq buffer (get-buffer buf)))))
        (setq buffer (agent-review))
        (with-current-buffer buffer
          (goto-char (point-min))
          (search-forward "+two")
          (beginning-of-line)
          (agent-review-context-comment)
          (goto-char (point-min))
          (search-forward "Needs attention")
          (beginning-of-line)
          (agent-review-context-comment)
          (agent-review-toggle-thread-state))
        (let* ((review-file (expand-file-name ".agent-review/feature/offline.json" repo))
               (review (agent-review-store-read review-file))
               (thread (car (alist-get 'threads review))))
          (should (equal 1 (length (alist-get 'threads review))))
          (should (equal 2 (length (alist-get 'messages thread))))
          (should (equal "resolved" (alist-get 'state thread))))))))

(provide 'agent-review-entrypoint-test)
;;; agent-review-entrypoint-test.el ends here
