;;; agent-review-remap-test.el --- Remap tests -*- lexical-binding: t; -*-

(require 'test-helper)

(defun agent-review-remap-test--thread (anchor)
  `((thread_id . "thread-1")
    (state . "open")
    (anchor . ,anchor)
    (anchor_status . "active")
    (remap_history . nil)
    (messages . nil)))

(ert-deftest agent-review-collect-diff-anchors-keeps-deleted-file-path ()
  (should (fboundp 'agent-review--collect-diff-anchors))
  (let* ((diff (string-join
                '("diff --git a/removed.txt b/removed.txt"
                  "deleted file mode 100644"
                  "index 1111111..0000000 100644"
                  "--- a/removed.txt"
                  "+++ /dev/null"
                  "@@ -1,2 +0,0 @@"
                  "-gone"
                  "-still gone")
                "\n"))
         (anchors (agent-review--collect-diff-anchors diff "base-1" "head-2"))
         (first (car anchors)))
    (should (equal "removed.txt" (alist-get 'path first)))
    (should (equal "LEFT" (alist-get 'side first)))
    (should (equal 1 (alist-get 'line first)))))

(ert-deftest agent-review-remap-thread-marks-remapped-with-history ()
  (should (fboundp 'agent-review--remap-thread))
  (let* ((thread (agent-review-remap-test--thread
                  '((base_commit . "base-old")
                    (head_commit . "head-old")
                    (path . "demo.txt")
                    (side . "RIGHT")
                    (line . 9)
                    (diff_hunk . "@@ -1,2 +1,3 @@"))))
         (candidates (list '((base_commit . "base-new")
                             (head_commit . "head-new")
                             (path . "demo.txt")
                             (side . "RIGHT")
                             (line . 2)
                             (diff_hunk . "@@ -1,2 +1,3 @@"))))
         (result (agent-review--remap-thread thread candidates "head-new" "2026-03-29T12:00:00Z"))
         (anchor (alist-get 'anchor result))
         (current-anchor (alist-get 'current_anchor result))
         (history (car (last (alist-get 'remap_history result)))))
    (should (equal "remapped" (alist-get 'anchor_status result)))
    (should (equal "head-old" (alist-get 'head_commit anchor)))
    (should (equal 9 (alist-get 'line anchor)))
    (should (equal "head-new" (alist-get 'head_commit current-anchor)))
    (should (equal 2 (alist-get 'line current-anchor)))
    (should (equal "remapped" (alist-get 'result history)))
    (should (equal "diff_hunk" (alist-get 'method history)))
    (should (equal "head-old"
                   (alist-get 'head_commit (alist-get 'from_anchor history))))
    (should (equal "head-new"
                   (alist-get 'head_commit (alist-get 'to_anchor history))))))

(ert-deftest agent-review-remap-thread-prefers-exact-line-match-over-hunk-match ()
  (should (fboundp 'agent-review--remap-thread))
  (let* ((thread (agent-review-remap-test--thread
                  '((base_commit . "base-old")
                    (head_commit . "head-old")
                    (path . "demo.txt")
                    (side . "RIGHT")
                    (line . 9)
                    (diff_hunk . "@@ -1,2 +1,3 @@"))))
         (candidates (list '((base_commit . "base-new")
                             (head_commit . "head-new")
                             (path . "demo.txt")
                             (side . "RIGHT")
                             (line . 2)
                             (diff_hunk . "@@ -1,2 +1,3 @@"))
                           '((base_commit . "base-new")
                             (head_commit . "head-new")
                             (path . "demo.txt")
                             (side . "RIGHT")
                             (line . 9)
                             (diff_hunk . "@@ -7,2 +7,4 @@"))))
         (result (agent-review--remap-thread thread candidates "head-new" "2026-03-29T12:00:00Z"))
         (current-anchor (alist-get 'current_anchor result))
         (history (car (last (alist-get 'remap_history result)))))
    (should (equal "line" (alist-get 'method history)))
    (should (equal 9 (alist-get 'line current-anchor)))
    (should (equal "@@ -7,2 +7,4 @@" (alist-get 'diff_hunk current-anchor)))))

(ert-deftest agent-review-remap-thread-marks-outdated-when-no-match ()
  (should (fboundp 'agent-review--remap-thread))
  (let* ((thread (agent-review-remap-test--thread
                  '((base_commit . "base-old")
                    (head_commit . "head-old")
                    (path . "demo.txt")
                    (side . "RIGHT")
                    (line . 9)
                    (diff_hunk . "@@ -1,2 +1,3 @@"))))
         (candidates (list '((base_commit . "base-new")
                             (head_commit . "head-new")
                             (path . "other.txt")
                             (side . "RIGHT")
                             (line . 2)
                             (diff_hunk . "@@ -5,2 +5,3 @@"))))
         (result (agent-review--remap-thread thread candidates "head-new" "2026-03-29T12:00:00Z"))
         (anchor (alist-get 'anchor result))
         (history (car (last (alist-get 'remap_history result)))))
    (should (equal "outdated" (alist-get 'anchor_status result)))
    (should (equal "head-old" (alist-get 'head_commit anchor)))
    (should (equal 9 (alist-get 'line anchor)))
    (should-not (alist-get 'current_anchor result))
    (should (equal "outdated" (alist-get 'result history)))
    (should (equal "none" (alist-get 'method history)))))

(ert-deftest agent-review-remap-anchors-updates-status-and-appends-event ()
  (should (fboundp 'agent-review-remap-anchors))
  (let* ((review (agent-review-test--sample-review
                  "/tmp/repo" "feature/offline" "main" "head-old" '("head-old")))
         (written nil)
         (diff (string-join
                '("diff --git a/demo.txt b/demo.txt"
                  "index 1111111..2222222 100644"
                  "--- a/demo.txt"
                  "+++ b/demo.txt"
                  "@@ -1,1 +1,2 @@"
                  " one"
                  "+two")
                "\n")))
    (setf (alist-get 'threads review)
          (list
           `((thread_id . "thread-1")
             (state . "open")
             (anchor . ((base_commit . "base-old")
                        (head_commit . "head-old")
                        (path . "demo.txt")
                        (side . "RIGHT")
                        (line . 2)
                        (diff_hunk . "@@ -1,1 +1,2 @@")))
             (anchor_status . "active")
             (remap_history . nil)
             (messages . nil))
           `((thread_id . "thread-2")
             (state . "open")
             (anchor . ((base_commit . "base-old")
                        (head_commit . "older-head")
                        (path . "missing.txt")
                        (side . "RIGHT")
                        (line . 4)
                        (diff_hunk . "@@ -4,1 +4,1 @@")))
             (anchor_status . "active")
             (remap_history . nil)
             (messages . nil))))
    (with-temp-buffer
      (agent-review-mode)
      (setq agent-review--review-file "/tmp/review.json"
            agent-review--review review)
      (cl-letf (((symbol-function 'agent-review-store-read)
                 (lambda (_file) (copy-tree review)))
                ((symbol-function 'agent-review-store-write)
                 (lambda (_file value)
                   (setq written (copy-tree value))
                   "/tmp/review.json"))
                ((symbol-function 'agent-review-git-head-commit)
                 (lambda (_repo-root) "head-new"))
                ((symbol-function 'agent-review-git-commit-list)
                 (lambda (_repo-root _base-ref) '("head-new")))
                ((symbol-function 'agent-review-git-rev-parse)
                 (lambda (_repo-root _rev) "base-new"))
                ((symbol-function 'agent-review-git-unified-diff)
                 (lambda (_repo-root _base-ref) diff)))
        (agent-review-remap-anchors))
      (let* ((events (alist-get 'events written))
             (last-event (car (last events)))
             (threads (alist-get 'threads written))
             (remapped (car threads))
             (outdated (cadr threads)))
        (should (equal "remapped" (alist-get 'anchor_status remapped)))
        (should (equal "outdated" (alist-get 'anchor_status outdated)))
        (should (equal "head-old" (alist-get 'head_commit (alist-get 'anchor remapped))))
        (should (equal "head-new" (alist-get 'head_commit (alist-get 'current_anchor remapped))))
        (should (equal "anchors_remapped" (alist-get 'kind last-event)))
        (should (equal 1 (alist-get 'remapped_count last-event)))
        (should (equal 1 (alist-get 'outdated_count last-event)))))))

(provide 'agent-review-remap-test)
;;; agent-review-remap-test.el ends here
