;;; agent-review-entrypoint-test.el --- Entrypoint tests -*- lexical-binding: t; -*-

(require 'test-helper)

(defun agent-review-test--face-contains-p (property face)
  "Return non-nil when PROPERTY includes FACE."
  (cond
   ((eq property face) t)
   ((listp property) (memq face property))
   (t nil)))

(ert-deftest agent-review-creates-a-new-offline-review ()
  (should (fboundp 'agent-review))
  (agent-review-test-with-temp-repo (repo)
    (let ((default-directory repo)
          (buffer nil))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _args) "main"))
                ((symbol-function 'switch-to-buffer)
                 (lambda (buf &rest _)
                   (setq buffer (get-buffer buf))))
                ((symbol-function 'pop-to-buffer)
                 (lambda (buf &rest _)
                   (setq buffer (get-buffer buf)))))
        (setq buffer (agent-review))
        (should (buffer-live-p buffer))
        (with-current-buffer buffer
          (should (derived-mode-p 'agent-review-mode))
          (should (string-match-p "Base: main" (buffer-string)))
          (should (string-match-p "Total 1 commits" (buffer-string)))
          (should (string-match-p "Files changed (1 files; 1 additions, 0 deletions)" (buffer-string)))
          (should (string-match-p "modified\\s-+a/demo.txt -> b/demo.txt" (buffer-string)))))
      (let ((review-file (expand-file-name ".agent-review/feature/offline.json" repo)))
        (should (file-exists-p review-file))))))

(ert-deftest agent-review-renders-styled-metadata-and-diff ()
  (agent-review-test-with-temp-repo (repo)
    (let ((default-directory repo)
          (buffer nil))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _args) "main"))
                ((symbol-function 'switch-to-buffer)
                 (lambda (buf &rest _)
                   (setq buffer (get-buffer buf))))
                ((symbol-function 'pop-to-buffer)
                 (lambda (buf &rest _)
                   (setq buffer (get-buffer buf)))))
        (setq buffer (agent-review))
        (with-current-buffer buffer
          (goto-char (point-min))
          (search-forward "Agent Review:")
          (should (agent-review-test--face-contains-p
                   (get-text-property (1- (point)) 'face)
                   'agent-review-title-face))
          (goto-char (point-min))
          (search-forward "Repo:")
          (should (agent-review-test--face-contains-p
                   (get-text-property (1- (point)) 'face)
                   'agent-review-meta-key-face))
          (goto-char (point-min))
          (re-search-forward "^@@ .+ @@")
          (beginning-of-line)
          (let ((face (or (get-text-property (point) 'face)
                          (get-text-property (point) 'font-lock-face))))
            (should (or (agent-review-test--face-contains-p face 'diff-hunk-header)
                        (agent-review-test--face-contains-p face 'magit-diff-hunk-heading))))
          (goto-char (point-min))
          (search-forward "+two")
          (beginning-of-line)
          (let ((face (or (get-text-property (point) 'face)
                          (get-text-property (point) 'font-lock-face))))
            (should (or (agent-review-test--face-contains-p face 'diff-added)
                        (agent-review-test--face-contains-p face 'diff-indicator-added)))))))))

(ert-deftest agent-review-tab-toggles-diff-file-section ()
  (agent-review-test-with-temp-repo (repo)
    (let ((default-directory repo)
          (buffer nil))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _args) "main"))
                ((symbol-function 'switch-to-buffer)
                 (lambda (buf &rest _)
                   (setq buffer (get-buffer buf))))
                ((symbol-function 'pop-to-buffer)
                 (lambda (buf &rest _)
                   (setq buffer (get-buffer buf)))))
        (setq buffer (agent-review))
        (with-current-buffer buffer
          (goto-char (point-min))
          (re-search-forward "^modified[[:space:]]+a/demo.txt -> b/demo.txt$")
          (beginning-of-line)
          (let ((section (magit-current-section)))
            (should (magit-file-section-p section))
            (should-not (eq section magit-root-section))
            (call-interactively #'magit-section-toggle)
            (should (oref section hidden))))))))

(ert-deftest agent-review-tab-toggles-metadata-and-commit-sections ()
  (agent-review-test-with-temp-repo (repo)
    (let ((default-directory repo)
          (buffer nil))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _args) "main"))
                ((symbol-function 'switch-to-buffer)
                 (lambda (buf &rest _) (setq buffer (get-buffer buf))))
                ((symbol-function 'pop-to-buffer)
                 (lambda (buf &rest _) (setq buffer (get-buffer buf)))))
        (setq buffer (agent-review))
        (with-current-buffer buffer
          (goto-char (point-min))
          (re-search-forward "^Metadata$")
          (beginning-of-line)
          (let ((meta-section (magit-current-section)))
            (should (eq (eieio-object-class-name meta-section) 'agent-review--metadata-section))
            (call-interactively #'magit-section-toggle)
            (should (oref meta-section hidden)))
          (goto-char (point-min))
          (re-search-forward "^Total 1 commits$")
          (beginning-of-line)
          (let ((commit-section (magit-current-section)))
            (should (eq (eieio-object-class-name commit-section) 'agent-review--commits-section))
            (call-interactively #'magit-section-toggle)
            (should (oref commit-section hidden))))))))

(ert-deftest agent-review-continues-or-replaces-existing-review ()
  (should (fboundp 'agent-review-store-read))
  (agent-review-test-with-temp-repo (repo)
    (let* ((head (agent-review-test--git repo "rev-parse" "HEAD"))
           (review-file (expand-file-name ".agent-review/feature/offline.json" repo))
           (seed (agent-review-test--sample-review repo "feature/offline" "main" head (list head))))
      (setf (alist-get 'events seed)
            '(((kind . "created")
               (created_at . "2026-03-29T00:00:00Z"))
              ((kind . "thread_replied")
               (created_at . "2026-03-29T00:05:00Z")
               (thread_id . "thread-seed"))))
      (agent-review-test--write-review-file review-file seed)
      (let ((default-directory repo)
            (continue-buffer nil)
            (responses '("main" "Continue")))
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (&rest _args)
                     (prog1 (car responses)
                       (setq responses (cdr responses)))))
                  ((symbol-function 'switch-to-buffer)
                   (lambda (buf &rest _) (setq continue-buffer (get-buffer buf))))
                  ((symbol-function 'pop-to-buffer)
                   (lambda (buf &rest _) (setq continue-buffer (get-buffer buf)))))
          (setq continue-buffer (agent-review))
          (with-current-buffer continue-buffer
            (should (string-match-p "Base: main" (buffer-string)))))
        (should (equal "review-seed"
                       (alist-get 'review_id (agent-review-store-read review-file)))))
      (let ((default-directory repo)
            (replace-buffer nil)
            (responses '("HEAD~1" "Replace")))
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (&rest _args)
                     (prog1 (car responses)
                       (setq responses (cdr responses)))))
                  ((symbol-function 'switch-to-buffer)
                   (lambda (buf &rest _) (setq replace-buffer (get-buffer buf))))
                  ((symbol-function 'pop-to-buffer)
                   (lambda (buf &rest _) (setq replace-buffer (get-buffer buf)))))
          (setq replace-buffer (agent-review))
          (with-current-buffer replace-buffer
            (should (string-match-p "Base: HEAD~1" (buffer-string)))))
        (let ((review (agent-review-store-read review-file)))
          (should (equal "HEAD~1" (alist-get 'base_ref review)))
          (should-not (equal "review-seed" (alist-get 'review_id review)))
          (should (equal '("created" "thread_replied" "created" "replaced")
                         (mapcar (lambda (event) (alist-get 'kind event))
                                 (alist-get 'events review)))))))))

(ert-deftest agent-review-open-compatibility-entrypoint-is-callable ()
  (should (fboundp 'agent-review-open))
  (should (fboundp 'agent-review-open-url))
  (agent-review-test-with-temp-repo (repo)
    (let ((default-directory repo)
          (buffer nil))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _args) "main"))
                ((symbol-function 'switch-to-buffer)
                 (lambda (buf &rest _)
                   (setq buffer (get-buffer buf))))
                ((symbol-function 'pop-to-buffer)
                 (lambda (buf &rest _)
                   (setq buffer (get-buffer buf)))))
        (setq buffer (agent-review-open "owner" "repo" 123 t "anchor" "last-read"))
        (should (buffer-live-p buffer))
        (with-current-buffer buffer
          (should (derived-mode-p 'agent-review-mode)))
        (should (buffer-live-p (agent-review-open-url "https://example.test/pr/123")))))))

(ert-deftest agent-review-context-commands-persist-immediately ()
  (should (fboundp 'agent-review-context-comment))
  (should (fboundp 'agent-review-toggle-thread-state))
  (agent-review-test-with-temp-repo (repo)
    (let ((default-directory repo)
          (responses '("main" "Needs attention" "Reply from agent"))
          (buffer nil))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _args)
                   (prog1 (car responses)
                     (setq responses (cdr responses)))))
                ((symbol-function 'read-string)
                 (lambda (&rest _args)
                   (prog1 (car responses)
                     (setq responses (cdr responses)))))
                ((symbol-function 'switch-to-buffer)
                 (lambda (buf &rest _) (setq buffer (get-buffer buf))))
                ((symbol-function 'pop-to-buffer)
                 (lambda (buf &rest _) (setq buffer (get-buffer buf)))))
        (setq buffer (agent-review))
        (with-current-buffer buffer
          (goto-char (point-min))
          (search-forward "+two")
          (beginning-of-line)
          (agent-review-context-comment)
          (goto-char (point-min))
          (search-forward "Needs attention")
          (beginning-of-line)
          (agent-review-context-comment)
          (agent-review-toggle-thread-state))
        (let* ((review-file (expand-file-name ".agent-review/feature/offline.json" repo))
               (review (agent-review-store-read review-file))
               (thread (car (alist-get 'threads review))))
          (should (equal 1 (length (alist-get 'threads review))))
          (should (equal 2 (length (alist-get 'messages thread))))
          (should (equal "resolved" (alist-get 'state thread))))))))

(ert-deftest agent-review-renders-comments-inline-in-diff ()
  (agent-review-test-with-temp-repo (repo)
    (let ((default-directory repo)
          (responses '("main" "Inline review note"))
          (buffer nil))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _args)
                   (prog1 (car responses)
                     (setq responses (cdr responses)))))
                ((symbol-function 'read-string)
                 (lambda (&rest _args)
                   (prog1 (car responses)
                     (setq responses (cdr responses)))))
                ((symbol-function 'switch-to-buffer)
                 (lambda (buf &rest _) (setq buffer (get-buffer buf))))
                ((symbol-function 'pop-to-buffer)
                 (lambda (buf &rest _) (setq buffer (get-buffer buf)))))
        (setq buffer (agent-review))
        (with-current-buffer buffer
          (goto-char (point-min))
          (search-forward "+two")
          (beginning-of-line)
          (agent-review-context-comment)
          (should-not (string-match-p "^PENDING:" (buffer-string)))
          (goto-char (point-min))
          (search-forward "+two")
          (re-search-forward "^> 1 comment from @")
          (beginning-of-line)
          (let ((face (or (get-text-property (point) 'face)
                          (get-text-property (point) 'font-lock-face))))
            (should (agent-review-test--face-contains-p
                     face
                     'agent-review-in-diff-thread-title-face)))
          (should (get-text-property (point) 'agent-review-thread-id))
          (search-forward "Reply")
          (let* ((button (button-at (1- (point))))
                 (face (and button (button-get button 'face))))
            (should (agent-review-test--face-contains-p face 'agent-review-button-face)))
          (should (string-match-p "Inline review note" (buffer-string))))))))

(ert-deftest agent-review-supports-multiline-comments-with-snapshot ()
  (agent-review-test-with-temp-repo (repo)
    (agent-review-test--write-file (expand-file-name "demo.txt" repo) "one\ntwo\nthree\n")
    (agent-review-test--git repo "add" "demo.txt")
    (agent-review-test--git repo "commit" "-m" "expand diff")
    (let ((default-directory repo)
          (responses '("main" "Multiline note"))
          (buffer nil))
      (cl-letf (((symbol-function 'completing-read)
                 (lambda (&rest _args)
                   (prog1 (car responses)
                     (setq responses (cdr responses)))))
                ((symbol-function 'read-string)
                 (lambda (&rest _args)
                   (prog1 (car responses)
                     (setq responses (cdr responses)))))
                ((symbol-function 'switch-to-buffer)
                 (lambda (buf &rest _) (setq buffer (get-buffer buf))))
                ((symbol-function 'pop-to-buffer)
                 (lambda (buf &rest _) (setq buffer (get-buffer buf)))))
        (setq buffer (agent-review))
        (with-current-buffer buffer
          (goto-char (point-min))
          (re-search-forward "^\\+two$")
          (beginning-of-line)
          (let ((start (point)))
            (re-search-forward "^\\+three$")
            (end-of-line)
            (let ((end (point)))
              (goto-char start)
              (push-mark start t t)
              (goto-char end)
              (setq mark-active t
                    transient-mark-mode t)
              (agent-review-context-comment)))
          (goto-char (point-min))
          (re-search-forward "demo.txt:2-3")
          (re-search-forward "^  @@ .+ @@$"))
        (let* ((review-file (expand-file-name ".agent-review/feature/offline.json" repo))
               (review (agent-review-store-read review-file))
               (thread (car (alist-get 'threads review)))
               (anchor (alist-get 'anchor thread))
               (snapshot (alist-get 'snapshot_diff_hunk thread)))
          (should (equal 2 (alist-get 'start_line anchor)))
          (should (equal "RIGHT" (alist-get 'start_side anchor)))
          (should (equal 3 (alist-get 'line anchor)))
          (should (string-match-p "^@@ .+ @@\n" snapshot))
          (should (string-match-p "^\\+two$" snapshot))
          (should (string-match-p "^\\+three$" snapshot)))))))

(ert-deftest agent-review-continue-marks-stale-thread-outdated ()
  (agent-review-test-with-temp-repo (repo)
    (let* ((head (agent-review-test--git repo "rev-parse" "HEAD"))
           (review-file (expand-file-name ".agent-review/feature/offline.json" repo))
           (review (agent-review-test--sample-review repo "feature/offline" "main" "stale-head" (list head))))
      (setf (alist-get 'threads review)
            '(((thread_id . "thread-stale")
               (state . "open")
               (anchor . ((base_commit . "base-old")
                          (head_commit . "stale-head")
                          (path . "demo.txt")
                          (side . "RIGHT")
                          (line . 2)
                          (diff_hunk . "@@ -1,1 +1,2 @@")))
               (anchor_status . "active")
               (remap_history . nil)
               (messages . nil))))
      (agent-review-test--write-review-file review-file review)
      (let ((default-directory repo)
            (buffer nil)
            (responses '("main" "Continue")))
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (&rest _args)
                     (prog1 (car responses)
                       (setq responses (cdr responses)))))
                  ((symbol-function 'switch-to-buffer)
                   (lambda (buf &rest _) (setq buffer (get-buffer buf))))
                  ((symbol-function 'pop-to-buffer)
                  (lambda (buf &rest _) (setq buffer (get-buffer buf)))))
          (setq buffer (agent-review))
          (with-current-buffer buffer
            (should (string-match-p "\\[open/outdated\\]" (buffer-string)))
            (goto-char (point-min))
            (re-search-forward "^\\[open/outdated\\]")
            (beginning-of-line)
            (let ((section (magit-current-section)))
              (should (eq (eieio-object-class-name section) 'agent-review--thread-section))
              (should (oref section hidden)))))
        (let* ((persisted (agent-review-store-read review-file))
               (thread (car (alist-get 'threads persisted))))
          (should (equal "outdated" (alist-get 'anchor_status thread))))))))

(ert-deftest agent-review-refresh-keeps-remapped-thread-when-current-anchor-matches-head ()
  (agent-review-test-with-temp-repo (repo)
    (let* ((head (agent-review-test--git repo "rev-parse" "HEAD"))
           (review-file (expand-file-name ".agent-review/feature/offline.json" repo))
           (review (agent-review-test--sample-review repo "feature/offline" "main" head (list head))))
      (setf (alist-get 'threads review)
            `(((thread_id . "thread-remapped")
               (state . "open")
               (anchor . ((base_commit . "base-old")
                          (head_commit . "older-head")
                          (path . "demo.txt")
                          (side . "RIGHT")
                          (line . 1)
                          (diff_hunk . "@@ -1,1 +1,2 @@")))
               (current_anchor . ((base_commit . "base-old")
                                  (head_commit . ,head)
                                  (path . "demo.txt")
                                  (side . "RIGHT")
                                  (line . 2)
                                  (diff_hunk . "@@ -1,1 +1,2 @@")))
               (anchor_status . "remapped")
               (remap_history . (((timestamp . "2026-03-29T01:00:00Z")
                                  (result . "remapped")
                                  (method . "line"))))
               (messages . nil))))
      (agent-review-test--write-review-file review-file review)
      (let ((default-directory repo)
            (buffer nil)
            (responses '("main" "Continue")))
        (cl-letf (((symbol-function 'completing-read)
                   (lambda (&rest _args)
                     (prog1 (car responses)
                       (setq responses (cdr responses)))))
                  ((symbol-function 'switch-to-buffer)
                   (lambda (buf &rest _) (setq buffer (get-buffer buf))))
                  ((symbol-function 'pop-to-buffer)
                   (lambda (buf &rest _) (setq buffer (get-buffer buf)))))
          (setq buffer (agent-review))
          (with-current-buffer buffer
            (agent-review-refresh)
            (should (string-match-p "\\[open/remapped\\]" (buffer-string)))))
        (let* ((persisted (agent-review-store-read review-file))
               (thread (car (alist-get 'threads persisted))))
          (should (equal "remapped" (alist-get 'anchor_status thread)))
          (should (equal head
                         (alist-get 'head_commit (alist-get 'current_anchor thread)))))))))

(ert-deftest agent-review-uncommitted-creates-uncommitted-review ()
  "Selecting 'uncommitted' creates a review with review_type uncommitted."
  (agent-review-test-with-temp-repo (repo)
    ;; Add uncommitted change
    (agent-review-test--write-file (expand-file-name "demo.txt" repo) "one\ntwo\nthree\n")
    (let ((default-directory repo)
          (review nil))
      (cl-letf (((symbol-function 'agent-review-git-prompt-base-ref)
                 (lambda (&optional _repo) "uncommitted"))
                ((symbol-function 'agent-review--open-buffer)
                 (lambda (_file r) (setq review r))))
        (agent-review))
      (should review)
      (should (equal "uncommitted" (alist-get 'review_type review)))
      (should (null (alist-get 'base_ref review)))
      (should (null (alist-get 'head_commits review))))))

(ert-deftest agent-review-uncommitted-recompute-always-outdated ()
  "Threads with nil head_commit should always be treated as outdated."
  (let* ((thread `((thread_id . "t1")
                   (state . "open")
                   (anchor_status . "active")
                   (anchor . ((base_commit . "abc123")
                              (head_commit . nil)
                              (path . "demo.txt")
                              (side . "RIGHT")
                              (line . 2)
                              (diff_hunk . "@@ -1 +1,2 @@")))))
         (result (agent-review--recompute-thread-status thread "def456")))
    (should (equal "outdated" (alist-get 'anchor_status result)))))

(ert-deftest agent-review-uncommitted-refresh-skips-head-update ()
  "Refresh should not update head_ref or head_commits for uncommitted reviews."
  (agent-review-test-with-temp-repo (repo)
    (agent-review-test--write-file (expand-file-name "demo.txt" repo) "one\ntwo\nthree\n")
    (let ((review (agent-review-store-create repo "feature/offline" nil nil nil "uncommitted")))
      (setq review (agent-review--refresh-review-state review repo))
      (should (null (alist-get 'head_ref review)))
      (should (null (alist-get 'head_commits review))))))

(provide 'agent-review-entrypoint-test)
;;; agent-review-entrypoint-test.el ends here
